name: blog content validation service native CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PROJECT_NAME: blog-content-validation-service
  PROJECT_VERSION: latest

jobs:
  build-and-push-native-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1.2.2
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GHCR_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Quarkus native image
        run: mvn clean package -Pnative --define quarkus.native.container-build=true -B

      - name: Build Docker image for native binary
        run: docker build -f src/main/docker/Dockerfile.native -t ${{ env.REGISTRY }}/getwombats/${{ env.PROJECT_NAME }}:${{ env.PROJECT_VERSION }} .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ${{ env.REGISTRY }}/getwombats/${{ env.PROJECT_NAME }}:${{ env.PROJECT_VERSION }}
